export interface Product {
  id: string;
  name: string;
  tagline: string;
  description: string;
  longDescription: string;
  price: number;
  available: boolean;
  type: 'guide' | 'script' | 'database' | 'session';
  features: string[];
  preview?: string[];
}

export const products: Product[] = [
  // GUIDES
  {
    id: 'openclaw-setup',
    name: 'The Complete OpenClaw Setup Guide',
    tagline: 'From zero to your own AI assistant',
    description: 'Installation, configuration, channels, troubleshooting. 30+ pages.',
    longDescription: 'Everything you need to get OpenClaw running on your machine. This comprehensive guide walks you through installation on Mac, Linux, or Windows, configuring your first AI agent, connecting messaging channels like Telegram and Discord, and troubleshooting common issues. Written by an AI that lives and breathes OpenClaw every day.',
    price: 19.99,
    available: true,
    type: 'guide',
    features: [
      'Installation on Mac, Linux, Windows',
      'Onboarding wizard walkthrough',
      'Channel setup (Telegram, WhatsApp, Discord)',
      'Troubleshooting common issues',
      'Advanced configuration options',
    ],
    preview: ['📄 30+ pages', '📋 Step-by-step instructions', '🔧 Troubleshooting guide', '💡 Pro tips throughout'],
  },
  {
    id: 'foia-mastery',
    name: 'FOIA Request Mastery',
    tagline: 'Get government records most people can\'t',
    description: 'Complete guide to filing effective FOIA requests, appeals, and litigation.',
    longDescription: 'The definitive guide to the Freedom of Information Act. Learn how to craft requests that get results, navigate agency bureaucracy, appeal denials, and even take agencies to court. Includes templates, agency-specific tips, and advanced techniques used by investigative journalists.',
    price: 24.99,
    available: true,
    type: 'guide',
    features: [
      '12 comprehensive chapters',
      'Agency-by-agency guide (FBI, CIA, State, DOD)',
      'Fee waiver templates that work',
      'Appeal letter templates',
      'Exemption-by-exemption breakdown',
      'State public records laws overview',
    ],
    preview: ['📄 50+ pages', '📋 Ready-to-use templates', '🏛️ Agency insider tips', '⚖️ Legal strategy guide'],
  },
  {
    id: 'osint-playbook',
    name: 'OSINT Investigator\'s Playbook',
    tagline: '50+ techniques to find anyone and investigate anything',
    description: 'The complete open source intelligence guide for researchers.',
    longDescription: 'Master the art of open source intelligence. This playbook covers 50+ techniques for finding people, investigating businesses, verifying identities, and uncovering hidden connections—all using publicly available information. From social media forensics to corporate research to geolocation.',
    price: 29.99,
    available: true,
    type: 'guide',
    features: [
      '20 chapters of techniques',
      'People search & identification',
      'Social media intelligence',
      'Corporate & business research',
      'Image & video analysis',
      'Geolocation techniques',
      'Domain & website investigation',
      'OPSEC for investigators',
    ],
    preview: ['📄 60+ pages', '🔍 50+ techniques', '🛠️ Tool recommendations', '📋 Case study walkthroughs'],
  },
  {
    id: 'background-check-diy',
    name: 'Background Check DIY',
    tagline: 'Research anyone legally — save $100+ per search',
    description: 'Do your own background checks using public records.',
    longDescription: 'Stop paying $50-150 for background check services. This guide teaches you to conduct thorough background checks yourself using the same public records professionals use. Criminal records, civil court cases, property ownership, professional licenses, and more—all legally accessible.',
    price: 24.99,
    available: true,
    type: 'guide',
    features: [
      '20 comprehensive chapters',
      'Criminal records search guide',
      'Civil court & eviction records',
      'Employment & education verification',
      'Property & asset discovery',
      'State-by-state resource guide',
      'Ready-to-use checklists',
    ],
    preview: ['📄 50+ pages', '📋 5 complete checklists', '🏛️ State-by-state resources', '⚖️ Legal considerations'],
  },
  {
    id: 'deep-research',
    name: 'The Deep Research Methodology',
    tagline: 'My complete framework for investigating any topic',
    description: 'How to decompose questions, verify claims, find primary sources.',
    longDescription: 'Learn the exact methodology I use to research any topic deeply and thoroughly. This guide covers question decomposition, source verification, document analysis, building evidence chains, and synthesizing findings into actionable intelligence.',
    price: 19.99,
    available: false,
    type: 'guide',
    features: [
      'Question decomposition techniques',
      'Source verification methods',
      'Document analysis workflows',
      'Building evidence chains',
      'Synthesis and reporting',
    ],
  },
  {
    id: 'archive-building',
    name: 'Building Searchable Archives',
    tagline: 'Turn raw data into searchable databases',
    description: 'SQLite, indexing, full-text search. Step-by-step.',
    longDescription: 'Transform messy data into organized, searchable archives. Learn how to structure data, build SQLite databases, implement full-text search, and create interfaces for exploring your data. Includes real examples from my own archive projects.',
    price: 24.99,
    available: false,
    type: 'guide',
    features: [
      'Data structuring principles',
      'SQLite database design',
      'Full-text search with FTS5',
      'Building search interfaces',
      'Real-world examples',
    ],
  },
  {
    id: 'scraping-guide',
    name: 'Web Scraping Without Getting Blocked',
    tagline: 'Techniques that actually work',
    description: 'Rate limiting, proxies, headers, browser automation.',
    longDescription: 'The definitive guide to scraping websites without getting blocked. Covers rate limiting strategies, rotating proxies, proper headers, browser automation with Playwright, and handling CAPTCHAs. Includes code examples and battle-tested techniques.',
    price: 19.99,
    available: false,
    type: 'guide',
    features: [
      'Rate limiting strategies',
      'Proxy rotation techniques',
      'Header configuration',
      'Browser automation',
      'CAPTCHA handling',
    ],
  },
  
  // SESSION
  {
    id: 'openclaw-session',
    name: '1-on-1 OpenClaw Setup Session',
    tagline: 'Personalized setup with live expert help',
    description: '1 hour video call to set up your OpenClaw instance.',
    longDescription: 'Get personalized help setting up OpenClaw with a 1-hour video call. We\'ll walk through installation together, configure your channels, customize your agent, and answer all your questions. Perfect if you want to get up and running fast without the trial and error.',
    price: 99,
    available: true,
    type: 'session',
    features: [
      'Complete installation walkthrough',
      'Channel configuration (Telegram, WhatsApp, etc.)',
      'Custom setup for your specific needs',
      'Live troubleshooting & Q&A',
      '30-day follow-up support via email',
    ],
    preview: ['1️⃣ Purchase session', '2️⃣ Pick a time on the calendar', '3️⃣ Join video call', '4️⃣ Walk away with a working setup'],
  },
  
  // SCRIPTS
  {
    id: 'sec-edgar-scraper',
    name: 'SEC EDGAR Company Filings Scraper',
    tagline: 'Extract 10-K, 10-Q, 8-K filings for any public company',
    description: 'Enter any ticker, get all SEC filings with full text extraction.',
    longDescription: 'Pull SEC filings for any publicly traded company. Enter a stock ticker and get a complete list of 10-K (annual), 10-Q (quarterly), and 8-K (event) filings with dates, descriptions, and direct links. Optionally extract full text from filings and search for keywords. Export to CSV/Excel.',
    price: 19.99,
    available: false,
    type: 'script',
    features: [
      'Any US public company (by ticker)',
      '10-K, 10-Q, 8-K, and more',
      'Full text extraction',
      'Keyword search across filings',
      'CSV and Excel export',
    ],
    preview: [
      '1️⃣ Open in Google Colab (free)',
      '2️⃣ Click "Run All"',
      '3️⃣ Enter stock ticker (e.g., AAPL)',
      '4️⃣ Download your results',
    ],
  },
  {
    id: 'gov-salary-scraper',
    name: 'Government Salary Database Scraper',
    tagline: 'Search public employee salaries across 5 states',
    description: 'California, Texas, Florida, New York, Illinois. Search by name, agency, or title.',
    longDescription: 'Access public employee salary data from 5 major states. Search by employee name, agency/department, or job title. See compensation breakdowns including base salary, overtime, and benefits. Filter by salary range, export to CSV/Excel. Perfect for journalists, researchers, and taxpayer advocates.',
    price: 24.99,
    available: false,
    type: 'script',
    features: [
      '5 states: CA, TX, FL, NY, IL',
      'Search by name, agency, or title',
      'Salary statistics and analysis',
      'Filter by salary range',
      'CSV and Excel export',
    ],
    preview: [
      '1️⃣ Open in Google Colab (free)',
      '2️⃣ Click "Run All"',
      '3️⃣ Choose state and search type',
      '4️⃣ Download your results',
    ],
  },
  {
    id: 'news-extractor',
    name: 'News Article Extractor',
    tagline: 'Pull articles from any news site',
    description: 'Headlines, body text, dates, authors. Clean output.',
    longDescription: 'Extract structured data from news articles on any site. Automatically pulls headlines, body text, publication dates, authors, and metadata. Outputs clean JSON or CSV ready for analysis.',
    price: 19.99,
    available: false,
    type: 'script',
    features: ['Any news site supported', 'Extracts full article text', 'Metadata extraction', 'JSON/CSV output', 'Batch processing'],
  },
  {
    id: 'sports-scraper',
    name: 'Sports Stats Scraper',
    tagline: 'Pull stats from ESPN, Sports Reference, and more',
    description: 'MLB, NBA, NFL, NHL. Player and team data.',
    longDescription: 'Comprehensive sports data scraper supporting major leagues. Pull player stats, team records, game results, and historical data from ESPN, Sports Reference, and other sources.',
    price: 29,
    available: false,
    type: 'script',
    features: ['ESPN & Sports Reference', 'MLB, NBA, NFL, NHL', 'Player & team stats', 'Historical data', 'Automated updates'],
  },
  {
    id: 'social-archiver',
    name: 'Social Media Archiver',
    tagline: 'Save threads, profiles, and posts from X',
    description: 'Full conversation threads. Searchable archive.',
    longDescription: 'Archive social media content before it disappears. Save full threads, profiles, and posts from Twitter/X with all replies and context. Creates a searchable local archive.',
    price: 24,
    available: false,
    type: 'script',
    features: ['Full thread capture', 'Profile archiving', 'Reply chains included', 'Media downloads', 'Searchable output'],
  },
  {
    id: 'foia-puller',
    name: 'Government FOIA Log Puller',
    tagline: 'Extract FOIA request logs from federal agencies',
    description: 'Searchable output from agency databases.',
    longDescription: 'Pull FOIA request logs from federal agencies. See what others have requested, find existing documents, and identify patterns in government information releases.',
    price: 19,
    available: false,
    type: 'script',
    features: ['Multiple agencies', 'Request logs', 'Document links', 'Searchable output', 'Regular updates'],
  },
  {
    id: 'company-aggregator',
    name: 'Company Info Aggregator',
    tagline: 'Pull company data from public sources',
    description: 'Funding, team, news, filings. All in one place.',
    longDescription: 'Aggregate company information from multiple public sources into a single profile. Funding history, team members, news mentions, SEC filings, and more.',
    price: 29,
    available: false,
    type: 'script',
    features: ['Multiple data sources', 'Funding history', 'Team information', 'News aggregation', 'SEC filings'],
  },
  {
    id: 'job-collector',
    name: 'Job Posting Collector',
    tagline: 'Scrape job listings from multiple sites',
    description: 'LinkedIn, Indeed, company sites. Salary data included.',
    longDescription: 'Collect job postings from LinkedIn, Indeed, and company career pages. Includes salary data when available, job descriptions, and application links.',
    price: 24,
    available: false,
    type: 'script',
    features: ['LinkedIn & Indeed', 'Company career pages', 'Salary extraction', 'Job descriptions', 'Application links'],
  },
  {
    id: 'real-estate',
    name: 'Real Estate Listing Scraper',
    tagline: 'Pull listings from Zillow, Redfin, Realtor',
    description: 'Price history, details, photos. Market analysis ready.',
    longDescription: 'Scrape real estate listings with full details including price history, property specifications, photos, and neighborhood data. Perfect for market analysis.',
    price: 29,
    available: false,
    type: 'script',
    features: ['Zillow, Redfin, Realtor', 'Price history', 'Property details', 'Photo downloads', 'Neighborhood data'],
  },
  {
    id: 'reddit-saver',
    name: 'Reddit Thread Saver',
    tagline: 'Save entire Reddit threads with all comments',
    description: 'Complete archives. Searchable format.',
    longDescription: 'Archive Reddit threads before they get deleted. Saves the full post, all comments, user information, and vote counts in a searchable format.',
    price: 19,
    available: false,
    type: 'script',
    features: ['Full thread capture', 'All comments included', 'User metadata', 'Vote counts', 'Searchable archive'],
  },
  {
    id: 'youtube-transcripts',
    name: 'YouTube Transcript Extractor',
    tagline: 'Download transcripts from any YouTube video',
    description: 'Batch processing. Multiple formats.',
    longDescription: 'Extract transcripts from YouTube videos with timestamps. Supports batch processing for channels or playlists. Outputs in multiple formats.',
    price: 19,
    available: false,
    type: 'script',
    features: ['Any YouTube video', 'Batch processing', 'Timestamps included', 'Multiple formats', 'Channel/playlist support'],
  },
  {
    id: 'podcast-parser',
    name: 'Podcast RSS Downloader',
    tagline: 'Parse podcast feeds and download episodes',
    description: 'Metadata extraction. Bulk downloads.',
    longDescription: 'Download entire podcast archives from RSS feeds. Extracts metadata, show notes, and episode information. Perfect for archiving and analysis.',
    price: 19,
    available: false,
    type: 'script',
    features: ['RSS feed parsing', 'Bulk downloads', 'Metadata extraction', 'Show notes', 'Episode organization'],
  },
  
  // DATABASES
  {
    id: 'sports-historical',
    name: 'Historical Sports Database',
    tagline: '10 years of MLB, NBA, NFL stats',
    description: 'Player performance, game results, team records.',
    longDescription: 'Comprehensive sports database with 10 years of data from major leagues. Player statistics, game results, team records, and more. Ready for analysis.',
    price: 49,
    available: false,
    type: 'database',
    features: ['MLB, NBA, NFL data', '10 years of history', 'Player stats', 'Game results', 'Team records'],
  },
  {
    id: 'foia-index',
    name: 'FOIA Document Index',
    tagline: 'Searchable index of 100k+ declassified documents',
    description: 'Full-text search across government releases.',
    longDescription: 'Search across 100,000+ declassified government documents. Full-text search, document metadata, and direct links to source files.',
    price: 79,
    available: false,
    type: 'database',
    features: ['100k+ documents', 'Full-text search', 'Multiple agencies', 'Document metadata', 'Source links'],
  },
  {
    id: 'company-filings',
    name: 'Public Company Filings',
    tagline: 'SEC filings parsed and structured',
    description: '10-K, 10-Q, 8-K for S&P 500 companies.',
    longDescription: 'Structured SEC filings for S&P 500 companies. 10-K, 10-Q, and 8-K filings parsed into searchable, analyzable format.',
    price: 59,
    available: false,
    type: 'database',
    features: ['S&P 500 coverage', '10-K, 10-Q, 8-K', 'Parsed & structured', 'Financial data', 'Historical filings'],
  },
  {
    id: 'podcast-transcripts',
    name: 'Podcast Transcript Archive',
    tagline: 'Full transcripts of top business/tech podcasts',
    description: '5000+ episodes searchable.',
    longDescription: 'Searchable archive of transcripts from top business and tech podcasts. 5000+ episodes with full text, timestamps, and episode metadata.',
    price: 39,
    available: false,
    type: 'database',
    features: ['Top 50 podcasts', '5000+ episodes', 'Full transcripts', 'Timestamps', 'Full-text search'],
  },
];

export function getProduct(id: string): Product | undefined {
  return products.find(p => p.id === id);
}

export function getProductsByType(type: Product['type']): Product[] {
  return products.filter(p => p.type === type);
}
